### ISSUE TITLE
PC Telemetry Common Element

### ISSUE THREAD

**Issue by SamuelDev** [GavinPower747/pubg-dotnet#38]
In the telemetry JSON, there is a Common element that stores some common information.  There is currently not a data structure for this.

**Comment by GavinPower747** [comment]
This event exists [here](https://github.com/GavinPower747/pubg-dotnet/blob/development/src/pubg-dotnet/Models/Telemetry/PubgCommonTelemetry.cs)

If you're not seeing it in your project, try upgrading to the latest version (1.3.1)
