### ISSUE TITLE
Player death type error

### ISSUE THREAD

**Issue by SamuelDev** [GavinPower747/pubg-dotnet#42]
There is a player death type in the match object for 'logout'.  When this appears in the match, the json parser breaks.  See error below:

Newtonsoft.Json.JsonSerializationException: 'Error converting value "logout" to type 'Pubg.Net.Models.Participants.PubgParticipantDeathType'. Path 'included[187].attributes.stats.deathType'.'

ArgumentException: Requested value 'logout' was not found.

**Comment by GavinPower747** [comment]
Good catch, will update the enum and release in 1.3.2

**Comment by GavinPower747** [comment]
I'll also create an issue on the Pubg documentation repo, since they don't list it there.

**Comment by GavinPower747** [comment]
So has been released for over a week now so I'm going to go ahead and close this
