### ISSUE TITLE
PubgGameModeStats killpoints missing?

### ISSUE THREAD

**Issue by yvanruth** [GavinPower747/pubg-dotnet#47]
Hello I must wanted to know there i will be able to find killpoints, so I can calculate ratings for players when I search them. Is it not implemented on the models yet or just not available from the API?

**Comment by yvanruth** [comment]
I have just read on the PUBG Dev api that aggregated stats is on the roadmap, but the date was not specified yet. Untill then we have to calculate ourselves by retrieving all matches for a player and aggregating. In my case that would be a little bit too much as we try to serve 400+ registered rated users on our discord :). Thanks for checking tho!

**Comment by GavinPower747** [comment]
Not a problem, I'm going to close this issue now.
