### ISSUE TITLE
Killpoints missing

### ISSUE THREAD

**Issue by yvanruth** [GavinPower747/pubg-dotnet#49]
Hello,

I want to inform you that killpoints does get responsed back from the API. You can add a new jsonpropperty to your 'PubgGameModeStats' model. Here is an example of response for the player/season object:

{  
   "data":{  
      "type":"playerSeason",
      "attributes":{  
         "gameModeStats":{  
            "duo":{  
               "assists":2,
               "boosts":2,
               "dBNOs":2,
               "dailyKills":0,
               "damageDealt":1009.8745,
               "days":3,
               "headshotKills":1,
               "heals":8,
               **"killPoints":1074.6542,**
               "kills":5,
               "longestKill":133.63144,
               "longestTimeSurvived":1743.825,
               "losses":6,
               "maxKillStreaks":1,
               "mostSurvivalTime":1743.825,
               "revives":1,
               "rideDistance":7857.7017,
               "roadKills":0,
               "roundMostKills":3,
               "roundsPlayed":6,
               "suicides":0,
               "teamKills":0,
               "timeSurvived":5953.2993,
               "top10s":2,
               "vehicleDestroys":1,
               "walkDistance":9712.629,
               "weaponsAcquired":33,
               "weeklyKills":5,
               "winPoints":1509.8591,
               "wins":0
            },
            "duo-fpp":{  
               "assists":0,
               "boosts":0,
               "dBNOs":0,
               "dailyKills":0,
               "damageDealt":0,
               "days":0,
               "headshotKills":0,
               "heals":0,
               **"killPoints":0,**
               "kills":0,
               "longestKill":0,
               "longestTimeSurvived":0,
               "losses":0,
               "maxKillStreaks":0,
               "mostSurvivalTime":0,
               "revives":0,
               "rideDistance":0,
               "roadKills":0,
               "roundMostKills":0,
               "roundsPlayed":0,
               "suicides":0,
               "teamKills":0,
               "timeSurvived":0,
               "top10s":0,
               "vehicleDestroys":0,
               "walkDistance":0,
               "weaponsAcquired":0,
               "weeklyKills":0,
               "winPoints":0,
               "wins":0
            },
            "solo":{  
               "assists":0,
               "boosts":0,
               "dBNOs":0,
               "dailyKills":0,
               "damageDealt":0,
               "days":0,
               "headshotKills":0,
               "heals":0,
               **"killPoints":0,**
               "kills":0,
               "longestKill":0,
               "longestTimeSurvived":0,
               "losses":0,
               "maxKillStreaks":0,
               "mostSurvivalTime":0,
               "revives":0,
               "rideDistance":0,
               "roadKills":0,
               "roundMostKills":0,
               "roundsPlayed":0,
               "suicides":0,
               "teamKills":0,
               "timeSurvived":0,
               "top10s":0,
               "vehicleDestroys":0,
               "walkDistance":0,
               "weaponsAcquired":0,
               "weeklyKills":0,
               "winPoints":0,
               "wins":0
            },
            "solo-fpp":{  
               "assists":0,
               "boosts":0,
               "dBNOs":0,
               "dailyKills":0,
               "damageDealt":0,
               "days":0,
               "headshotKills":0,
               "heals":0,
               **"killPoints":0,**
               "kills":0,
               "longestKill":0,
               "longestTimeSurvived":0,
               "losses":0,
               "maxKillStreaks":0,
               "mostSurvivalTime":0,
               "revives":0,
               "rideDistance":0,
               "roadKills":0,
               "roundMostKills":0,
               "roundsPlayed":0,
               "suicides":0,
               "teamKills":0,
               "timeSurvived":0,
               "top10s":0,
               "vehicleDestroys":0,
               "walkDistance":0,
               "weaponsAcquired":0,
               "weeklyKills":0,
               "winPoints":0,
               "wins":0
            },
            "squad":{  
               "assists":10,
               "boosts":11,
               "dBNOs":15,
               "dailyKills":15,
               "damageDealt":3683.1875,
               "days":2,
               "headshotKills":4,
               "heals":57,
               **"killPoints":1238.0754,**
               "kills":19,
               "longestKill":205.73648,
               "longestTimeSurvived":1936.159,
               "losses":14,
               "maxKillStreaks":2,
               "mostSurvivalTime":1936.159,
               "revives":4,
               "rideDistance":19546.547,
               "roadKills":0,
               "roundMostKills":9,
               "roundsPlayed":15,
               "suicides":1,
               "teamKills":1,
               "timeSurvived":11421.584,
               "top10s":5,
               "vehicleDestroys":1,
               "walkDistance":15032.113,
               "weaponsAcquired":61,
               "weeklyKills":19,
               "winPoints":1532.7582,
               "wins":1
            },
            "squad-fpp":{  
               "assists":0,
               "boosts":0,
               "dBNOs":0,
               "dailyKills":0,
               "damageDealt":0,
               "days":0,
               "headshotKills":0,
               "heals":0,
               **"killPoints":0,**
               "kills":0,
               "longestKill":0,
               "longestTimeSurvived":0,
               "losses":0,
               "maxKillStreaks":0,
               "mostSurvivalTime":0,
               "revives":0,
               "rideDistance":0,
               "roadKills":0,
               "roundMostKills":0,
               "roundsPlayed":0,
               "suicides":0,
               "teamKills":0,
               "timeSurvived":0,
               "top10s":0,
               "vehicleDestroys":0,
               "walkDistance":0,
               "weaponsAcquired":0,
               "weeklyKills":0,
               "winPoints":0,
               "wins":0
            }
         }
      },
      "relationships":{  
         "matchesDuoFPP":{  
            "data":[  

            ]
         },
         "matchesSquad":{  
            "data":[  
               {  
                  "type":"match",
                  "id":"a32e06ef-5bd7-4d06-ab0d-3dbb4ce7bd65"
               },
               {  
                  "type":"match",
                  "id":"17e91315-dc86-4858-86d5-ef469215b0b8"
               },
               {  
                  "type":"match",
                  "id":"03693880-fcea-4c04-9a75-1e235ddd6af8"
               },
               {  
                  "type":"match",
                  "id":"84456e9b-eca4-4086-981f-76f90f2ffb1e"
               },
               {  
                  "type":"match",
                  "id":"b7415e80-4826-4cb9-b54c-f015e98944b6"
               },
               {  
                  "type":"match",
                  "id":"1c54626b-9342-4617-b230-ab3e03530d4f"
               },
               {  
                  "type":"match",
                  "id":"b6b1a4f2-ba65-428a-8aae-34f30593c246"
               },
               {  
                  "type":"match",
                  "id":"9c21ce77-5bae-4be0-8348-ddeb92e38bbe"
               },
               {  
                  "type":"match",
                  "id":"ecaf4ab7-0b54-4330-b7d8-a41bcd2fad65"
               },
               {  
                  "type":"match",
                  "id":"d77b1ebe-8ed1-460e-aee7-dd9134120805"
               },
               {  
                  "type":"match",
                  "id":"a1ece7f7-049c-40e3-aac2-b1b02f5b3cd6"
               },
               {  
                  "type":"match",
                  "id":"9c426ea9-d43b-4938-8c70-f192c4cac663"
               },
               {  
                  "type":"match",
                  "id":"969903e8-139d-41de-9124-02a25881feee"
               },
               {  
                  "type":"match",
                  "id":"de8fbddc-f9ee-4d93-a0f7-2424eb813e6d"
               },
               {  
                  "type":"match",
                  "id":"a4c264f5-08ff-498e-9806-eac6ec54e106"
               }
            ]
         },
         "matchesSquadFPP":{  
            "data":[  

            ]
         },
         "season":{  
            "data":{  
               "type":"season",
               "id":"division.bro.official.2018-05"
            }
         },
         "player":{  
            "data":{  
               "type":"player",
               "id":"account.ba5d32b3d4d84625990d6e5528e16c48"
            }
         },
         "matchesSolo":{  
            "data":[  

            ]
         },
         "matchesSoloFPP":{  
            "data":[  

            ]
         },
         "matchesDuo":{  
            "data":[  
               {  
                  "type":"match",
                  "id":"5827fe44-e39a-429d-9bcb-feeeed251969"
               },
               {  
                  "type":"match",
                  "id":"a15e3a20-9d18-48ac-8fd5-8ae6fe5bff9b"
               },
               {  
                  "type":"match",
                  "id":"5ac47e70-1e6b-46ef-8a50-d968233c7554"
               },
               {  
                  "type":"match",
                  "id":"9ab99c69-f96f-488a-9035-508077975883"
               },
               {  
                  "type":"match",
                  "id":"884436e0-236c-4557-8932-751a1512c259"
               },
               {  
                  "type":"match",
                  "id":"81bdf95f-2edd-4889-86f9-98aa68f7ffab"
               }
            ]
         }
      }
   },
   "links":{  
      "self":"https://api.playbattlegrounds.com/shards/pc-eu/players/account.ba5d32b3d4d84625990d6e5528e16c48/seasons/division.bro.official.2018-05"
   },
   "meta":{  
   }
}

**Comment by GavinPower747** [comment]
Building: https://ci.appveyor.com/project/GavinPower747/pubg-dotnet/build/1.3.4.92

**Comment by GavinPower747** [comment]
https://www.nuget.org/packages/Pubg-DotNet/1.3.4

Validating on NuGet at the moment should be available soon.

**Comment by yvanruth** [comment]
Thanks!

**Comment by GavinPower747** [comment]
Since you've not reported any issues, I'm going to go ahead and close this issue now.
