### ISSUE TITLE
Suggestion - Region Enum

### ISSUE THREAD

**Issue by ItsNovaHere** [GavinPower747/pubg-dotnet#5]
I think we should have an enum for the regions instead of having to memorize. Either 2 different enums for each platform or just a joint enum.

I'll start working on this if I get the time.

(I'm just gonna help with tweaks and make the API easier to use ?)

**Comment by ItsNovaHere** [comment]
I've started work on it, should I put the enum-to-string class/method in the same .cs file or separate it?

**Comment by GavinPower747** [comment]
Yeah moving the regions to enums is definitely something that I intended to do. Probably the thing to do is rather than having a ToString on it, I have a json converter in another project that will just convert it to a string at serialization so we just deal with it as the enum and then let newtonsoft take care of converting it to a string behind the scenes.

**Comment by GavinPower747** [comment]
My mistake actually it's built into Json.Net I'll use the game modes for example

```C#
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

    [JsonConverter(typeof(StringEnumConverter))]
    public enum PubgGameMode
    {
        [EnumMember(value = "squad")]
        Squad,
        [EnumMember(value = "solo")]
        Solo,
        [EnumMember(value = "duo")]
        Duo
    }
```

**Comment by GavinPower747** [comment]
And yeah definitely any suggestions you can come up with feel free to throw in an issue or DM me on Discord

**Comment by GavinPower747** [comment]
I'll be out for the rest of the night (I'm in GMT) but I'll respond first thing in the morning

**Comment by ItsNovaHere** [comment]
Ah okay. I'll use the JsonConverter then.

**Comment by ItsNovaHere** [comment]
I don't know enough about GitHub, but do you think you could give me permissions to push to the repository? Both GitHub desktop and the Visual Studio plugin like to fuck me over.

**Comment by GavinPower747** [comment]
Added you as a Contributor, will review the PR now

**Comment by GavinPower747** [comment]
PR Merged Closing
