### ISSUE TITLE
PUBG new Map

### ISSUE THREAD

**Issue by ZUBAT** [GavinPower747/pubg-dotnet#60]
Savage please add in Models/Match/PubgMap.cs 

i have catch
Error converting value "Savage_Main" to type 'Pubg.Net.PubgMap'. Path 'data.attributes.mapName'.

**Comment by ZUBAT** [comment]
#61  close

**Comment by GavinPower747** [comment]
https://ci.appveyor.com/project/GavinPower747/pubg-dotnet/build/1.6.1.117

Building now, will automatically release when it's complete

**Comment by GavinPower747** [comment]
https://www.nuget.org/packages/Pubg-DotNet/1.6.1

V1.6.1 is live apologies for the delay
