### ISSUE TITLE
GetPubgMatchesRequest is missing

### ISSUE THREAD

**Issue by Arrowka** [GavinPower747/pubg-dotnet#64]
Hello. First of all, thank you for your NuGet.

My problem is i cant find **GetPubgMatchesRequest**.
And **GetPlayers** always run into nullref ex. 

Im developing Xamarin.Forms app.

**Comment by GavinPower747** [comment]
Hi there,

The documentation in the readme appears to have slightly gone out of date. In the start when the API was first released you used to request matches and then you'd be able to get player information from the matches. Now that has slightly changed and you have two ways of going about it.

1a: If you want matches from a specific player and you know their ID: 
```csharp
    var playerService = new PubgPlayerService();
    var matchService = new PubgMatchService();

    var player = playerService.GetPlayer(PubgRegion.PCEurope, "yourplayerid");
    var matches = matchService.GetMatch(PubgRegion.PCEurope, player.MatchIds.First());
```

1b: If you want matches from a specific player and don't know their ID:
```csharp
    var playerService = new PubgPlayerService();
    var matchService = new PubgMatchService();

    var playerRequest = new GetPubgPlayersRequest()
    {
        PlayerNames = new string[] { "YourPlayerName" } 
    };

    var player = playerService.GetPlayer(PubgRegion.PCEurope, "myplayerid");
    var match = matchService.GetMatch(PubgRegion.PCEurope, player.MatchIds.First());
```

Note: matches can only be gotten one by one but they do NOT count against your rate limit.

2: You just want matches and don't care about the players.
```csharp
    var sampleService = new PubgSamplesService();
    var matchService = new PubgMatchService();

    var matchSampleIds = sampleService.GetMatchSamples(PubgRegion.PCEurope);
    var match = matchService.GetMatch(PubgRegion.PCEurope, matchSampleIds.MatchIds.First());
```

As for get GetPlayers throwing a null ref, could you show me the request that you're passing into the method?

**Comment by Arrowka** [comment]
Thank you! :) 

The next question is where can i find rating, and match rank? Api is not sending this datas? I cant find it in the onjects.

**Comment by GavinPower747** [comment]
The match rank (what place the player/squad finished) is on the PubgRoster if that's what you mean. I'm not sure what rating your looking for but I'd reccomend looking at either the PubgParticipantStats or the PubgSeasonStats you should be able to either find or calculate something from there.

**Comment by GavinPower747** [comment]
Actually, I just glanced over at the Pubg API Discord and happened to see someone sharing information on how to calculate the rating

Rating = Win point + 0.2 * Kill point

So you can find the win points and kill points for either a match or season on their respective stats objects (PubgParticipantStats or PubgSeasonStats) and then run them through that formula to get the rating for either the match or the season

**Comment by GavinPower747** [comment]
@Arrowka Can I close this issue or is there still more problems that you're having?

**Comment by Arrowka** [comment]
Yeah, you can close! Thanks for your help!

**Comment by GavinPower747** [comment]
Not a problem, feel free to reach out anytime! :)
