### ISSUE TITLE
Create more documentation

### ISSUE THREAD

**Issue by GavinPower747** [GavinPower747/pubg-dotnet#65]
We need to create more documentation. We need to cover some basic operations like retrieving matches, players and other entities.

**Comment by dan-drews** [comment]
Hi,

I might take a stab at this one if I have a chance soon

**Comment by oahmed-OS** [comment]
I'm looking to utilize this SDK for a project and would be willing to assist with this. Do you have any guidelines you would like followed for documentation?

**Comment by GavinPower747** [comment]
I'm not too pushed on a format that it might take. I'm just of the opinion that as the creator I'll take things for granted and assume people know things when they won't, so I'd like to be as hands off with the docs as possible and let the users who are using it in the trenches on a day to day basis decide what should be in there and what the best way to write it would be.

**Comment by oahmed-OS** [comment]
Created documentation to most of the main calls in the wiki of https://github.com/oahmed-OS/pubg-dotnet-Wiki. Can copy what is currently in the readme and include it in the home page or remove the home page. Also not sure if having sample variable declarations is helpful (i.e: var playerId = {SOME PLAYER ID HERE}) Thoughts on the current state of the documentation? 

Side note: If you plan on managing the wiki in a repository or cloning it locally to perform the edits, we will need to remove colons from page titles as that doesn;t play nice with the cloning process and makes the pages appear missing on your local machine
