### ISSUE TITLE
Warmodefpp Game Mode Not Found

### ISSUE THREAD

**Issue by nordy1145** [GavinPower747/pubg-dotnet#67]
Creating a new MatchService, it appears to be throwing an exception when the game mode type is "warmodefpp" or assuming "warmodetpp" (I don't play third person).  

  | Name | Value | Type
-- | -- | -- | --
◢ | InnerException | {System.ArgumentException: Requested value 'warmodefpp' was not found.    at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, String value, Boolean disallowNumber)    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)} | System.Exception {System.ArgumentException}

  | Name | Value | Type
-- | -- | -- | --
  | Message | "Requested value 'warmodefpp' was not found." | string

Here is an example of a match that throws the error.
var matchService = new PubgMatchService("APIKEYHERE").GetMatch(PubgRegion.PCNorthAmerica,"46661de3-92e4-4842-9500-c2eaed0f7f63")

**Comment by GavinPower747** [comment]
Hey man, good catch. 

Should be sorted by this PR #68

I'm hoping to get a release out in the next hour or so to fix the issue.

**Comment by nordy1145** [comment]
Sweet! Thanks!!

**Comment by GavinPower747** [comment]
#71 going through CI now, should release automatically after it's merged

**Comment by GavinPower747** [comment]
I'll create a PR to the Pubg API docs too since they don't actually have those game modes listed

**Comment by GavinPower747** [comment]
Forgot to merge before I left for the gym, my bad!

Release build has started now: https://ci.appveyor.com/project/GavinPower747/pubg-dotnet/build/1.6.1.133

After that's finished nuget will take a few minutes to verify and it'll be live

**Comment by nordy1145** [comment]
I see a few more Game modes that are not defined.  Below are the GameModes and an example MatchID.

Not sure how many more of these modes there will be and if there is a better way to handle these since it seems they are creating new modes on a regular basis...

Message	"Error converting value \"acpfpp\" to type 'Pubg.Net.PubgGameMode'. Path 'data.attributes.gameMode'."	string
		matchID	"b7d42d9d-6d40-4022-b834-ca9e8dcf6072"	string

Message	"Error converting value \"flarefpp\" to type 'Pubg.Net.PubgGameMode'. Path 'data.attributes.gameMode'."	string
			matchID	"c4d6766b-9f44-4bdc-8836-a37c734fb7e6"	string

Message	"Error converting value \"flaregunfpp\" to type 'Pubg.Net.PubgGameMode'. Path 'data.attributes.gameMode'."	string
		matchID	"cde6bd4c-9835-4efb-aa7d-d9ee11c0e8fd"	string

Message	"Error converting value \"pgifpp\" to type 'Pubg.Net.PubgGameMode'. Path 'data.attributes.gameMode'."	string
		matchID	"6e4d51b7-543d-49d8-8940-b9dacf25aff2"	string

**Comment by GavinPower747** [comment]
Hey man sorry, I've been out of the country for the past while. They seem to be throwing everything and anything into there with absolutely no warning, I may have to just make that field a string.

**Comment by nordy1145** [comment]
No worries!  Yeah it does seem like that.  Hard to keep constants when they throw whatever/whenever without a notice.  Hopefully the trips were good!

**Comment by GavinPower747** [comment]
Apologies for the delay but the first version with the string has been launched

https://www.nuget.org/packages/Pubg-DotNet/1.8.0

**Comment by nordy1145** [comment]
Sorry for the delay, but it all looks good now!
