### ISSUE TITLE
		Message	"Unable to find specified resource"	string

### ISSUE THREAD

**Issue by nordy1145** [GavinPower747/pubg-dotnet#79]
Getting the following message when trying to get match info

  | Name | Value | Type
-- | -- | -- | --
  | Message | "Unable to find specified resource" | string

var matchService = new PubgMatchService(apiKey);
var matchInfo = matchService.GetMatch(PubgRegion.PCNorthAmerica, "8ab32840-2254-41cb-9d11-e903cbe709be");

Updated to the latest version, but haven't had a chance to review the source yet.

**Comment by GavinPower747** [comment]
Hey there,

That particular exception is thrown when the API returns a 404. I've checked it myself and that particular match does not exist.

**Comment by GavinPower747** [comment]
Potentially needs better messaging, I'll update that to something more specific to the library.

**Comment by GavinPower747** [comment]
Going to close this now since there has been no reply in a while
