### ISSUE TITLE
Json Exception

### ISSUE THREAD

**Issue by ZUBAT** [GavinPower747/pubg-dotnet#83]
On function matchService.GetMatchPC(match.matchid);
catch JsonException
Error converting value 63676723200 to type 'System.Int32'. Path 'data.attributes.duration'.

**Comment by GavinPower747** [comment]
Interesting, it's overflowed the value for a 32 bit integer.

If that's milliseconds that would mean the match lasted 736 Days... 

I'll bump up the variable to an int64 none the less but could you give me the match id for that match?

**Comment by ZUBAT** [comment]
matchid 8526cd07-d4fb-416a-81f8-8a7c5bee4383 region eu
