### ISSUE TITLE
New map 'DihorOtok_Main' 

### ISSUE THREAD

**Issue by ZUBAT** [GavinPower747/pubg-dotnet#89]
Error converting value "DihorOtok_Main" to type 'Pubg.Net.PubgMap'. Path 'data.attributes.mapName'.
Requested value 'DihorOtok_Main' was not found.

**Comment by GavinPower747** [comment]
Apologies for the delay man, been out of the country for a few days

**Comment by GavinPower747** [comment]
This will be a part of 2.1.1 out in a few minutes

**Comment by ZUBAT** [comment]
@GavinPower747 not problem)
